coverage:
  status:
    project:
      default:
        target: 0.9
        threshold: 0.01
    patch:
      default:
        target: 0.9
        threshold: 0.01

comment:
  layout: "reach, diff, flags, files"
  require_changes: false
