export {
  createProposedSpecificationChange,
  createSpecificationAdapterSupport,
  createSpecificationDecision,
  createSpecificationDecisionRecord,
  createSpecificationOperation,
  createSpecificationSourceSnapshot,
} from "./factory";
export { createPortableIntegrationReference } from "./portable-target";
export type {
  PortableIntegrationReference,
  PortableIntegrationReferenceInput,
  PortableSpecificationTarget,
} from "./portable-target";
export type * from "./semantic-types";
export type {
  ProposedSpecificationChange,
  ProposedSpecificationChangeId,
  SpecificationAdapterFixture,
  SpecificationAdapterSourceOwnership,
  SpecificationAdapterSupport,
  SpecificationDiagnostic,
  SpecificationDiagnosticImpact,
  SpecificationDiagnosticSeverity,
  SpecificationOperation,
  SpecificationOperationDisposition,
  SpecificationOperationId,
  SpecificationOperationMatrix,
  SpecificationSourceContract,
  SpecificationDecision,
  SpecificationDecisionRecord,
  SpecificationDecisionRecordId,
  SpecificationDecisionSummary,
  SpecificationDecisionValidity,
  SpecificationDocumentNodeKind,
  SpecificationEvidenceBinding,
  SpecificationFormat,
  SpecificationPolicyVersion,
  SpecificationQuestion,
  SpecificationNodeKind,
  SpecificationNode,
  SpecificationSemanticNodeKind,
  SpecificationSourceAuthority,
  SpecificationSourceBinding,
  SpecificationSourceDocument,
  SpecificationSourceId,
  SpecificationSourceRevisionBinding,
  SpecificationSourceRole,
  SpecificationSourceSnapshot,
} from "./types";
